=== alexandremaldonado-design/ASIX-LLM-Alexandre-Maldonado-Fuentes/Practica4.4/cifp.dtd
<!ELEMENT cifp (alumne|professor)*>

<!ELEMENT alumne (nom, llinatges, data_naixement?, correu?, telefon?, adreça?, data_matricula, curs)>
<!ATTLIST alumne
    id ID #REQUIRED
>

<!ELEMENT professor (nom, llinatges, data_naixement?, correu?, telefon?, adreça?, data_incorporacio, departament, assignatura*)>
<!ATTLIST professor
    id ID #REQUIRED
>

<!ELEMENT nom (#PCDATA)>
<!ELEMENT llinatges (#PCDATA)>
<!ELEMENT data_naixement (#PCDATA)>
<!ELEMENT correu (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>
<!ELEMENT adreça (#PCDATA)>

<!ELEMENT data_matricula (#PCDATA)>
<!ELEMENT curs (#PCDATA)>

<!ELEMENT data_incorporacio (#PCDATA)>
<!ELEMENT departament (#PCDATA)>

<!ELEMENT assignatura (nom_assignatura)>
<!ATTLIST assignatura
    id_assignatura ID #REQUIRED
>

<!ELEMENT nom_assignatura (#PCDATA)>
<!ATTLIST nom_assignatura
    cicle (DAM | DAW | ASIX | SMX | SEIA | ER | AUT) #REQUIRED
    data_inici CDATA #IMPLIED
    data_final CDATA #IMPLIED
>

=== alexandremaldonado-design/ASIX-LLM-Alexandre-Maldonado-Fuentes/Practica4.4/alumnes_professors_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cifp SYSTEM "cifp.dtd">
<cifp>
    <alumne id="1">
        <nom>Joan</nom>
        <llinatges>Garcia Perelló</llinatges>
        <data_naixement>2005-03-15</data_naixement>
        <correu>jgarcia@cifppau.cat</correu>
        <telefon>971201234</telefon>
        <adreça>Carrer de l'Escola, 1</adreça>
        <data_matricula>2023-09-01</data_matricula>
        <curs>DAM</curs>
    </alumne>
    
    <alumne id="10">
        <nom>Maria</nom>
        <llinatges>Nicolau Rosselló</llinatges>
        <data_naixement>2006-07-22</data_naixement>
        <correu>mnicolau@cifppau.cat</correu>
        <data_matricula>2024-09-01</data_matricula>
        <curs>SMX</curs>
    </alumne>
    
    <professor id="P101">
        <nom>Pere</nom>
        <llinatges>Martínez Serra</llinatges>
        <data_naixement>1980-11-02</data_naixement>
        <correu>pmartinez@cifppau.cat</correu>
        <telefon>971202345</telefon>
        <data_incorporacio>2015-09-15</data_incorporacio>
        <departament>Informàtica</departament>
        <assignatura id_assignatura="A101">
            <nom_assignatura cicle="DAM" data_inici="2024-09-15" data_final="2025-06-20">Programació</nom_assignatura>
        </assignatura>
        <assignatura id_assignatura="A102">
            <nom_assignatura cicle="DAW">Entorns de desenvolupament</nom_assignatura>
        </assignatura>
    </professor>
</cifp>>
